_G["__ls_reached_redirect"] = true
local wcmaybvheyjc = "t062aoyh5egc0lcqog"
local bgorocae = "y0i4kbb09fbpgi6"
local myxbymzrepqnkz = "k8j9uumfz1"
local mczdeqbrl = "jwzbhdejibdsa"
local ypzusbuyxlmyl = "so5tlew0dvtm27"
local jzytftojlkkr = "8s94dnule2y221s"
local mwidtsmxqwykz = "6ozggfa2h95g9"
local jotdwixnx = "b989pebrpd"
local ljcgjtzkedjpq = "m9c57b10b6x2xgwdyz"
local qbntjiaciyj = "psjoak0oq5hb21"
local tmcjcziwkenmx = "ysdjp3fyxviy52"
local sjpuexceix = "y77kk3whq0nv"
local xzoogdzwcuuv = "1042y85jc4kufz"
if _G["lazybear0340"] ~= true then return end
local aqmawtofrvsdmm = "9xzhfuok1gagntkcg7"
local zoxhlbblfs = "xpjgjzut5v94d"
local vzalfiuwx = "j6bg6irf9tjmp8"
local ucyhjyvui = "b59aripxxrezkby"
local ytkdugtkkl = "jco50w82gjuza"
local fwchnsxkje = "fyhgsjxztij7"
local mwxubiqr = "8tfqb0i9ithvcxlz"
local lihbqzepy = "uw5xx0j0ccw1a"
local sudozxta = "9548nnk2xtr"
local nzulmizu = "58brp9c3el8zt"
local sutajmxqotz = "k7sv9jwrxz2d"
local kwnztlownmbn = "95ift58qr3g"
local tcwovezn = "vbw7vkvhjm"
_G["pqdlxalqt"] = "3z24in17ptakwll"
local pgmslcfuutz = "vz6125iar7o27"
local vcbpgwvfbetlmt = "j3x046fbih2tebwlbq"
local idkgzzclvdili = "9xmxthzp7xop9w8i"
local ytjoihwqpwkvyh = "yf8lkr0yh5rtic"
local yppgsywerls = "mgbl2nt0kx"
local pasiqscade = "pkg76o1xiul5"
local dobdgfhurn = "6u2tso4yqyf6y7m"
local jsioqpljc = "x8dohahhijz6z752"
local wewzlnsuhdt = "p2id83o26sawh5cmpv"
local mdoirijl = "4kaltltjdlh"
local mbjuczpwkwk = "3kgbqh1c8s05kf4yb"
local qdktyvlwa = "260t5rcxamwhh1w"
local iqjeewxmpuelc = "71r97lak7ge"
local djaiquvplywa = "wqfgfj7jbhopoq38jdqr9"
local otaetrpaiptqlp = tostring(_G["Key"] or "")
_G["kvsbehogd"] = auth
local erajiygnyirjyq = tostring(game:GetService("Players").LocalPlayer.UserId)
local zjttagichfc = tostring(game.PlaceId)
local oleqqokrbry = "https://lazybear-gateway.iusemaybehook.workers.dev/?file=contentfiltered_test.lua&token=UPq0_py6_el-ZRLIQazEYaAdkPuYnK0R8WNb7Hh4Z3c&ck=" .. djaiquvplywa .. "&sv=3z24in17ptakwll&uid=" .. erajiygnyirjyq .. "&pid=" .. zjttagichfc .. "&key=" .. otaetrpaiptqlp .. "&hwid=" .. erajiygnyirjyq
local jhhjqzoft = game:HttpGet(oleqqokrbry, true)
loadstring(jhhjqzoft)()
_G["kvsbehogd"] = nil
