_G["__ls_reached_redirect"] = true
local buvintgk = "17s4zo426z5"
local hsombpfjgpocqr = "a1tkzit7ij"
local vyncrymlcarwg = "kp7jrvhrk90"
local ofovtbnwpujzd = "fow650cjah"
local gkcuyaonystgxr = "27g23xkib1xmlth1ix"
local yrdfbhysgf = "nd1aeet97he1"
local juylacwduin = "cdbxiq23jvhf"
local bnmsbfxecpiqw = "tp6kgdb9ph5"
local ecnqlvxlg = "t6htlxe14b41n07d"
local aiquvwvipcmhs = "fj0x6nv68k"
local afdqmbxavo = "ac80z3lv2k6071t"
local ztbicchaa = "y03tkgxl8i1ql2"
if _G["lazybear0340"] ~= true then return end
local umpeerweqlnkb = "pllrc7c1zr"
local aykbitcbxrsdvp = "q9lgavbxm3b8zu1"
local qccixdafbemn = "h3eoq2ktx2py9x"
local dikdljduxuuwm = "khbek45nyy3si"
local dhcvptjbbwtnbj = "uz2mbwuac81sb62bx"
local yszhnmlfwwg = "0i0f485moih77"
local wjvbwyimnbegux = "3pgopxoimq19lchvo6"
local nvfjgyegcnwy = "miip7uamr3e5ksmy"
local shwgscwwn = "6dy9qb6yzkyxr5"
local xcytbbbkfsx = "itwaaoe9qhvks76x0m"
local xhnwmowcwetjy = "tephhxmvc3x9wbtbzu"
local hjeojius = "nkznl68nfc"
_G["xgvrljrzu"] = "k5n0muqs3qo88a0czylo"
local igwiwkjzv = "s4ualfopsk5"
local gazhdqcnvcac = "418ordm9dmpj"
local nsreojuknvyk = "pipr80ezw6"
local hkpcyagygjn = "o9ut0mrasmjgfq4"
local ocbrvjvxmtdcbs = "3uq0nvcr8nvg"
local tygyjftwlurbj = "v0ab28ungr46pcubhy"
local tzsuonnkwfnlos = "g98p356ix14zt"
local xlcaicqmn = "v9wsmkg77l"
local xqplbxvky = "bkyam1i338xfd0x"
local vervziuj = "7rhem01c85oj"
local emchcnlkao = "dvkoqdx64p5u8ceb"
local yzxfslim = "gqkhhaqxyyz87cf"
local dcnsovth = "ide0svy3qpngjc9"
local lbanpwjjfww = tostring(_G["Key"] or "")
_G["rveyovnltb"] = auth
local wikxyzowfvras = tostring(game:GetService("Players").LocalPlayer.UserId)
local wosrvquit = tostring(game.PlaceId)
local fqcxtqgjyh = "https://lazybear-gateway.iusemaybehook.workers.dev/?file=lazybear0340_123.lua&token=WfDj5KdPUH6uLJD9Y5xGDXOh5vSp62EQPXhzSsAqvqk&ck=" .. dcnsovth .. "&sv=k5n0muqs3qo88a0czylo&uid=" .. wikxyzowfvras .. "&pid=" .. wosrvquit .. "&key=" .. lbanpwjjfww .. "&hwid=" .. wikxyzowfvras
local zielfunbitdnh = game:HttpGet(fqcxtqgjyh, true)
loadstring(zielfunbitdnh)()
_G["rveyovnltb"] = nil
